bitcrowd/bitstyles

stats/css.json

- Css-stats fell behind on last PR
Has **linting** and **testing** been conducted?

Updated css stats

---

gulpfile.js
package.json
stats/css.json

Fixes #185.
- Remove sourcemaps from the built version of the CSS — that should be what’s shippable to the browser, right now it’s >90% source map comment
- Also removed the source maps npm package as we don’t use it anywhere else
Has **linting** and **testing** been conducted?

Removes the sourcemaps from built version CSS.

---

bitstyles/bitstyles.scss
bitstyles/bitstyles/objects/_block.scss
bitstyles/bitstyles/objects/_flex.scss
bitstyles/bitstyles/objects/_media.scss
bitstyles/bitstyles/tools/_block.scss
bitstyles/bitstyles/tools/_flex.scss
bitstyles/bitstyles/tools/_media.scss

Fixes #187.
- New mixins created to define  `.o-media`, `.o-flex`, & `.o-block`. These can then be used to create breakpoint-dependent versions in client projects. 
Have any **object** or **trumps** components been updated? (delete this if not)
Has **linting** and **testing** been conducted?

Adds mixins for media, flex & block objects

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #202 .
- Adds a reminder to rum CSS stats generate script to PR template
Have any **object** or **trumps** components been updated? (delete this if not)
Has **linting** and **testing** been conducted?

Adds reminder to generate CSS stats to PR template.

---

bower.json
lib/bitstyles/version.rb
package.json

- removes the bower `private` flag
- Updates the version ready for tagging & publishing

Bump version & remove private flag

---

README.md

Incomplete fix for #221 — needs the travis badge.
- Adds npmjs badge to README
- Adds bower badge to README
- Adds rubygems badge to README

Adds npm, bower, & rubygems badges to the readme

---

scss/bitstyles/objects/_hidden.scss
scss/bitstyles/objects/_visuallyhidden.scss
scss/bitstyles/settings/_hidden.scss
scss/bitstyles/settings/_visuallyhidden.scss

Fixes #240 
- Renamed `$hidden-breakpoints` to `$bitstyles-hidden-breakpoints`
- Renamed `$visuallyhidden-breakpoints` to `$bitstyles-visuallyhidden-breakpoints`

[#240] breakpoints variables aren’t namespaced

---

package.json

Fixes #241 
- Added `npm run css:stats` to the `checks` task.

[#241] add css:stats to the checks task

---

package.json

Fixes #233
- Updates sc-5 styleguide dependency — version 1.3.3 had parsing issues, it’s now specified at minimum 1.4.1
- Removes the already-unused dependency on the deprecated `eslint-config-bitcrowd`.

[#233] npm run styleguide errors

---

scss/bitstyles/objects/_fixed-ratio.scss
scss/bitstyles/settings/_fixed-ratio.scss
scss/bitstyles/tools/_fixed-ratio.scss

Fixes #231 
- Made the `fixed-ratio` mixin a little more general, now accepts width & height parameters to set its ratio.
- Added a new mixin to generate variations without re-specifying all the base declarations.
- Factored out the calculation of ratio into a function.

[#231] add parameters to the fixed ratio mixin

---

scss/bitstyles/objects/_icon.scss
scss/bitstyles/settings/_icon.scss
scss/bitstyles/tools/_typography.scss

Fixes #271 
- `$bitstyles-icon-sizes` is now a correct Sass map.
- `@mixin generate-font-sizes` and `@mixin output-font-sizes` both updated to use the more concise Sass map `@each` iterator accessors (instead of one of the more verbose boilerplatey Sass accessor functions like `map-get` or `nth`).
Every time:

[#271] icon sizes should be specified in a map for consistency

---

package.json

Fixes #274 
- Tests now chained together using `;` instead of `&&`.
Every time:

[#274] Tests should continue even after one of them failed

---

bitstyles.gemspec
lib/bitstyles/version.rb
package.json

- Bumps version to 0.9.1
- Removes development-only files from the gem version
- Allows pushing gem to rubygems (now repo not private)
Every time:

Bumped version for rubygem version.

---

scss/bitstyles/tools/_typography.scss
test/css-stats.json
yarn.lock

Fixes #297
All font-sizes are now specified in rem, including the base font-size on `html` 🎉

no longer need to support px for font-size

---

package.json
scss/bitstyles/layout/object-cover/_.scss
yarn.lock

More dependency updates
- update to newest `styleint-config-bitcrowd`
- update the other packages, but still two minimalist packages at a bad version number left

Chore/update dependencies 2020.03.23

---

scss/bitstyles/settings/_checkbox.scss
scss/bitstyles/settings/_figure.scss
scss/bitstyles/settings/_radio.scss

Adds missing `!default` to all the Sass variables that were missing them, to allow overriding by library consumers
Fixes #335

Missing `!default`s

---

scss/bitstyles/generic/_box-sizing.scss

Adds a height to HTML, and a min-height to body, to ensure the body element and its background color always fill the screen
Fixes #336

[#336] Add html height

---

scss/bitstyles/base/forms/forms.stories.js
scss/bitstyles/settings/_global.color-palette.scss
scss/bitstyles/settings/_input.scss
scss/bitstyles/tools/_input.scss

Fixes #340 
Adds styles for invalid inputs:
- Updates `error` color to be less angry, more humane
- Adds text-color, border-colour & background-color variables for invalid inputs
- Adds a story to illustrate an invalid input (needs user input, as the browser will not render it invalid)

[#340] add colors for input invalid

---

scss/bitstyles/base/forms/_.scss

Applies the base radio & checkbox styles to checkboxes and radios, regardless of whether the browser supports `appearance: none`
Fixes #343

[#343] Apply margin to checkboxes & radio inputs

---

scss/bitstyles/base/typography/_.scss
scss/bitstyles/generic/_normalize.scss
scss/bitstyles/layout/grid/grid.md
scss/bitstyles/layout/grid/grid.stories.js
scss/bitstyles/layout/width/width.md
scss/bitstyles/objects/icon/icon.md
scss/bitstyles/objects/icon/icon.stories.js
scss/bitstyles/settings/_button--icon.scss
scss/bitstyles/settings/_button.scss
scss/bitstyles/settings/_checkbox.scss
scss/bitstyles/settings/_content.scss
scss/bitstyles/settings/_global.breakpoints.scss
scss/bitstyles/settings/_global.layout.scss
scss/bitstyles/settings/_global.typography.scss
scss/bitstyles/settings/_grid.scss
scss/bitstyles/settings/_hidden.scss
scss/bitstyles/settings/_icon.scss
scss/bitstyles/settings/_input.scss
scss/bitstyles/settings/_modal.scss
scss/bitstyles/settings/_select.scss
scss/bitstyles/settings/_topbar.scss
scss/bitstyles/settings/_width.scss
scss/bitstyles/tools/_fieldset.scss
scss/bitstyles/tools/_media.scss
scss/bitstyles/tools/_spacing.scss
scss/bitstyles/tools/_typography.scss
scss/bitstyles/utilities/hidden/hidden.stories.js
scss/bitstyles/utilities/margin/_.scss
scss/bitstyles/utilities/padding/_.scss
test/css-stats.json

Fixes #351
- Changes naming scheme of `spacing` from `small`, `medium` etc, to `s`, `m`, `xl`
- Updates naming of sized-based media queries to the shortened `s`, `m`, `l`, instead of small medium & large

[#351] Shorter size names

---

.travis.yml

Travis was complaining that the version of node set in `.travis.yml` was too low for one of the npm packages. this bumps node to v12.13.0

Bumps node version

---

scss/bitstyles/components/breadcrumbs.stories.mdx
scss/bitstyles/layout/box-alignment/_.scss
scss/bitstyles/objects/icon/settings.scss
scss/bitstyles/settings/_link.scss
scss/bitstyles/tools/_icon.scss
scss/bitstyles/utilities/fg/settings.scss
test/css-stats.json

Fixes #374 
Adds two breadcrumbs examples
Looks like:
Simple, with all text 
With an icon

[#374] Add component: breadcrumbs

---

.github/workflows/deploy-docs.yml
.storybook/main.js
.storybook/preview.js
README.md
package.json
yarn.lock

Fixes #389
- Adds gh-pages package, and a couple of new commands for deploying to github-pages to packagae.json
- Storybook will now default to show docs (when they exist for a component), and docs come first
- Updates storybook
Looks like: https://bitcrowd.github.io/bitstyles/

[#389] Publish static storybook to GitHub pages

---

.github/workflows/deploy-docs.yml
package.json

- Bumps version
- deploy to storybook now only happens on release published
On hold until the two remaining PRs are merged (will need rebase afterwards)

Bump version 1.0

---

scss/bitstyles.scss
scss/bitstyles/atoms/button--tab/_.scss
scss/bitstyles/atoms/button--tab/settings.scss
scss/bitstyles/atoms/button/settings.scss
scss/bitstyles/ui/section-heading.stories.mdx
scss/bitstyles/utilities/border/_.scss
scss/bitstyles/utilities/border/border.stories.mdx
scss/bitstyles/utilities/box-alignment/_.scss
scss/bitstyles/utilities/flex/_.scss

Fixes #407 
Adds some section headers, with variants labels, badges, and buttons.
Looks like:

[#407] Add component: header bars

---

scss/bitstyles/base/forms/forms.stories.mdx
scss/bitstyles/base/forms/inputs.stories.mdx
scss/bitstyles/base/forms/settings-input.scss
scss/bitstyles/base/forms/settings-select.scss
scss/bitstyles/tools/_select.scss

Fixes #394 
- Adds `:invalid` styles to the base select component
- Adds stories that show how to achieve it
Looks like:

[#394] Add select invalid styling

---

scss/bitstyles/atoms/button--danger/_.scss
scss/bitstyles/atoms/button--danger/settings.scss
scss/bitstyles/atoms/button--icon-reversed/_.scss
scss/bitstyles/atoms/button--icon-reversed/settings.scss
scss/bitstyles/atoms/button--icon/_.scss
scss/bitstyles/atoms/button--icon/settings.scss
scss/bitstyles/atoms/button--menu/_.scss
scss/bitstyles/atoms/button--menu/settings.scss
scss/bitstyles/atoms/button--mode/_.scss
scss/bitstyles/atoms/button--mode/settings.scss
scss/bitstyles/atoms/button--nav-large/_.scss
scss/bitstyles/atoms/button--nav-large/settings.scss
scss/bitstyles/atoms/button--nav/_.scss
scss/bitstyles/atoms/button--nav/settings.scss
scss/bitstyles/atoms/button--tab/_.scss
scss/bitstyles/atoms/button--ui/_.scss
scss/bitstyles/atoms/button--ui/settings.scss
scss/bitstyles/atoms/button/_.scss
scss/bitstyles/atoms/button/settings.scss
scss/bitstyles/base/forms/settings-checkbox.scss
scss/bitstyles/base/forms/settings-input.scss
scss/bitstyles/base/forms/settings-radio.scss
scss/bitstyles/base/forms/settings-select.scss
scss/bitstyles/tools/_input--checkbox.scss
scss/bitstyles/tools/_input--radio.scss
scss/bitstyles/tools/_input.scss
scss/bitstyles/tools/_select.scss
scss/bitstyles/ui/buttons.stories.mdx

Fixes #410 
All buttons now only set their border-color to override the base button styles, and for each of their hover/active/etc states. This simplifies the buttons a little, avoids the case where border-width is changed on hover/etc, and makes sure that all button types can be placed next to each other and have equal heights.
Not really any visual difference (the border is a _tiny_ bit thinner, as it’s based on font-size now), but here’s some of the buttons:

[#410] Equalise button borders

---

scss/bitstyles/atoms/button--ui/button--ui.stories.mdx
scss/bitstyles/atoms/button--ui/settings.scss
scss/bitstyles/atoms/button/_.scss
scss/bitstyles/atoms/dropdown/_.scss
scss/bitstyles/base/forms/settings-input.scss
scss/bitstyles/organisms/ui-group/ui-group.stories.mdx
scss/bitstyles/tools/_input.scss
scss/bitstyles/tools/_overflow.scss
scss/bitstyles/ui/dropdown-menu.stories.mdx
scss/bitstyles/ui/filter.stories.mdx
scss/bitstyles/ui/table.stories.mdx

Fixes #372 
Adds filtering and searching examples to the UI layer
Looks like:

[#372] Add component: search and filter

---

scss/bitstyles/ui/breadcrumbs.stories.mdx

Fixes #432 
Order of right-arrows and text labels in Breadcrumbs is switched, so that the last link always has an arrow after it, as the title of the current resource/object is normally the title after/below it.
Looks like:

[#431] Breadcrumb arrows to the right

---

scss/bitstyles.scss
scss/bitstyles/atoms/bordered-header/settings.scss
scss/bitstyles/base/forms/settings-fieldset.scss
scss/bitstyles/base/forms/settings-input.scss
scss/bitstyles/base/forms/settings-select.scss
scss/bitstyles/base/typography/_.scss
scss/bitstyles/tools/_bordered-header.scss
scss/bitstyles/tools/_select.scss
scss/bitstyles/ui/forms.stories.mdx
scss/bitstyles/utilities/gap/_.scss
scss/bitstyles/utilities/gap/gap.stories.mdx
scss/bitstyles/utilities/grid/_.scss
scss/bitstyles/utilities/grid/grid.stories.mdx

Fixes #429 
- Improved layout & visuals for non-login forms. Fieldsets, legends, and lots of grid to make it useful at different screensizes
- Adds an example for very simple forms
- Updates bordered-header to be left-aligned
- grid elements will now need to have the gap set using the gap utility classes.
Looks like:
Simple form has less chrome around it, and a restricted width:

[#429] Improve form examples

---

scss/bitstyles/atoms/button/_.scss
scss/bitstyles/atoms/content/_.scss
scss/bitstyles/atoms/content/settings.scss
scss/bitstyles/organisms/modal/_.scss
scss/bitstyles/organisms/modal/modal.stories.mdx
scss/bitstyles/organisms/modal/settings.scss
test/css-stats.json

Fixes #397 
Overhauls the modal styles, and the example components. Adds three example components:
- Simple informational modal
- Modal dialog with 2 options
- Modal with a long text for the user to read & accept
Looks like:

[#397] Update modal component

---

CHANGELOG.md
scss/bitstyles/atoms/button--icon/_.scss
scss/bitstyles/atoms/button--menu/_.scss
scss/bitstyles/atoms/button--nav-large/_.scss
scss/bitstyles/atoms/button--nav/_.scss
scss/bitstyles/ui/navbar.stories.mdx

Fixes #456 
- nav and icon buttons are no longer centered horizontally
- Navbar & sidebar examples are now in iframes to ensure the absolutely-positioned elements don’t bleed into the main page
Looks like:

[#456] Don’t center all button content

---

CHANGELOG.md
scss/bitstyles/atoms/dropdown/_.scss
scss/bitstyles/atoms/dropdown/dropdown.stories.mdx
scss/bitstyles/ui/dropdown-menu.stories.mdx
scss/bitstyles/ui/filter.stories.mdx
scss/bitstyles/ui/page-header.stories.mdx

Fixes #466 
- Adds a `.a-dropdown--top` variant of dropdown
- Renames `.a-dropdown--reverse` -> `.a-dropdown--right`
- Adds new example to atom & UI layers, updates existing dropdown examples
Looks like:

[#466] Dropdown component: add a ‘top’ variant

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #464 
- removes no-longer-relevant points from the PR template
- adds a reminder to update the changelog

[#464] Update PR template

---

CHANGELOG.md
scss/bitstyles/atoms/dropdown/_.scss
scss/bitstyles/atoms/dropdown/dropdown.stories.mdx
scss/bitstyles/ui/dropdown-menu.stories.mdx
scss/bitstyles/ui/sidebar.stories.mdx

Fixes #475 
- Adds a new dropdown variant that spans the full width of its nearest `position: relative` parent element
- Adds examples of this to the dropdown atom
- Adds examples of this to the UI dropdownmenu component
- Uses the new dropdown variant in the UI/sidebar component
Looks like:

[#475] Full-width dropdown in sidebar

---

.stylelintrc
CHANGELOG.md
package.json
scss/bitstyles/atoms/button--nav/_.scss
scss/bitstyles/atoms/button--small/_.scss
scss/bitstyles/atoms/button/_.scss
scss/bitstyles/settings/_layout.scss
scss/bitstyles/tools/_aspect-ratio.scss
scss/bitstyles/tools/_input--checkbox.scss
scss/bitstyles/tools/_input.scss
scss/bitstyles/tools/_typography-conversions.scss
yarn.lock

Fixes #493 
Migrating away from using the `/` as division, as Sass is doing so to avoid clashing with the meaning of the symbol in CSS (it’s increasingly being used there). See https://sass-lang.com/documentation/breaking-changes/slash-div
- Updates Sass to latest version, to allow the use of `Math.div`
- Uses the automatic migration tool to change all division to new method
- Updates the `input` mixin to use the new division method (was missed by automated migration)

[#493] Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

---

CHANGELOG.md
scss/bitstyles/ui/section-heading.stories.mdx
scss/bitstyles/ui/sidebar.stories.mdx
scss/bitstyles/utilities/border/_.scss
scss/bitstyles/utilities/border/border.stories.mdx
scss/bitstyles/utilities/border/settings.scss

Fixes #486 
border classes are now generated:
- all four directions by default
- border-color is now part of the classname
- uses the same generators as the margin/padding branch
- available at breakpoints if needed, but that’s not specified by default
- Adds stories for each of the border classes
Looks like:

[#486] Missing classes: borders

---

CHANGELOG.md
scss/bitstyles/tools/_input--checkbox.scss

Fixes #497
- Checkmark of checkboxes is now correctly centered, and only rendered once
Looked like:
Looks like:

[#497] Fix: checkboxes have little white dots

---

yarn.lock

Update trim-newlines package

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/tools/_directional-properties.scss
scss/bitstyles/utilities/z-index/_.scss
scss/bitstyles/utilities/z-index/settings.scss
scss/bitstyles/utilities/z-index/z-index.stories.mdx

Fixes #496 
- Adds a z-index utility class
- Adds the generator for non-directional properties, uses it generate z-indexes
- Adds docs on customizing z-indexes

[#496] Add utility class: z-index

---

CHANGELOG.md
scss/bitstyles/utilities/margin/margin.stories.mdx
scss/bitstyles/utilities/margin/settings.scss

Fixes #503 
- Adds `auto` to the available margin sizes
- Adds a story for it

[#503] Add utility: margin-auto

---

CHANGELOG.md
scss/bitstyles/utilities/gap/_.scss
scss/bitstyles/utilities/gap/gap.stories.mdx
scss/bitstyles/utilities/gap/settings.scss

Fixes #511 
- Uses the generator to output gap classes, therefore adds breakpoints
- Updates the docs a little

[#511] Responsive grid-gap classes

---

CHANGELOG.md
scss/bitstyles/atoms/button--nav-large/button--nav-large.stories.mdx
scss/bitstyles/organisms/modal/modal.stories.mdx
scss/bitstyles/organisms/navbar/navbar.stories.mdx
scss/bitstyles/organisms/notification-center/notification-center.stories.mdx
scss/bitstyles/ui/Colors.stories.js
scss/bitstyles/ui/app-layouts.stories.mdx
scss/bitstyles/ui/breadcrumbs.stories.mdx
scss/bitstyles/ui/button-groups.stories.mdx
scss/bitstyles/ui/dropdown-menu.stories.mdx
scss/bitstyles/ui/flashes.stories.mdx
scss/bitstyles/ui/forms.stories.mdx
scss/bitstyles/ui/navbar.stories.mdx
scss/bitstyles/ui/notifications.stories.mdx
scss/bitstyles/ui/page-header.stories.mdx
scss/bitstyles/ui/section-heading.stories.mdx
scss/bitstyles/ui/sidebar.stories.mdx
scss/bitstyles/ui/tabs.stories.mdx
scss/bitstyles/utilities/flex/_.scss
scss/bitstyles/utilities/flex/flex.stories.mdx
scss/bitstyles/utilities/flex/settings.scss
scss/bitstyles/utilities/items/_.scss
scss/bitstyles/utilities/items/items.stories.mdx
scss/bitstyles/utilities/items/settings.scss
scss/bitstyles/utilities/justify/_.scss
scss/bitstyles/utilities/justify/justify.stories.mdx
scss/bitstyles/utilities/justify/settings.scss
scss/bitstyles/utilities/self/_.scss
scss/bitstyles/utilities/self/self.stories.mdx
scss/bitstyles/utilities/self/settings.scss

Fixes #515 
- `.u-flex-`, `.u-items-`, `u-self-`, and `u-justify-` utility classes are all now generated, and consistently available at `m` breakpoint
- Updates docs & examples for flex, justify, items, and self utility classes
- Renames changed flex classnames (dropping the `__` notation

[#515] Make flex utility classes available at

---

.storybook/main.js
CHANGELOG.md
package.json
scss/bitstyles/base/forms/settings-checkbox.scss
scss/bitstyles/base/forms/settings-select.scss
scss/bitstyles/tools/_color.scss
scss/bitstyles/tools/_select.scss
yarn.lock

Fixes #440 
- Adds postcss-loader so we can use autoprefixer (it should be included in every project for browser-compatibility)
- Adds a function to tools.color to URL-encode hex colors
- Uses it to fix the URL-encoded SVGs used for the `<select>` arrows, and for checkboxes’ ✔
- All our color functions now use namespaced sass functions
Now even when post-css is not being used to build bitstyles, the select icons are visible, so the bug is fixed.
⚠️ without post-css (and therefore autoprefixer), the `appearance` property isn’t prefixed to `-webkit-appearance`, and therefore the browser’s built-in icon and ui-chrome may be visible next to ours, as shown here:
|Before|After|
|--|--| …

[#440] Select styles break without postcss?

---

CHANGELOG.md
scss/bitstyles/atoms/card/_card.scss
scss/bitstyles/atoms/card/_settings.scss
scss/bitstyles/atoms/card/card.stories.mdx
scss/bitstyles/ui/forms.stories.mdx
scss/bitstyles/utilities/col-span/_settings.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #527
- padding of cards is now handled inside the atom, instead of using padding utility classes
- so there are now multiple sizes of card — each applies a different padding
- added a `a-card__header` class that’s used in combination with those paddings to ensure an edge-to-edge subsection
- all is customizable with Sass variables
🚑 drive-by: grid-related classes are available at `l` breakpoint again (fixes the more complex form next to the login form example)
|Before|After|
|--|--|
|![before](https://user-images.githubusercontent.com/2479422/126310064-a231d534-cd5f-48a0-98e2-a1026d72f2e4.png)|![after2](https://user-images.githubusercontent.com/2479422/126309817-19764634-80d7-4a6c-8e7f-7cc5b4b18681.png)|
And:
Delete if not …

[#527] Login form with errors wrong spacing

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/atoms/card/_card.scss
scss/bitstyles/utilities/row-start/_index.import.scss
scss/bitstyles/utilities/row-start/_index.scss
scss/bitstyles/utilities/row-start/_row-start.scss
scss/bitstyles/utilities/row-start/_settings.scss
scss/bitstyles/utilities/row-start/row-start.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #538 
- Adds row-start utility classes

[#538] Add utility: row-start

---

CHANGELOG.md
package.json

- Bumps version to 3.0.0
- updates changleog to roll together all the changes from the two RCs

Bump version 3.0.0

---

CHANGELOG.md
scss/bitstyles/atoms/dl/dl.stories.mdx
scss/bitstyles/ui/dl.stories.mdx

Fixes #554 
- Example `dl`s are now aligned to baseline

[#554] Align dt/dd to baseline

---

CHANGELOG.md
scss/bitstyles/atoms/dropdown/_dropdown.scss

Fixes #560 
- Removes the hard-coded border properties, now handled only by the variable. Nothing to show visually here because it was not an issue in bitstyles build (as postcss was correcting the invalid border property) but was an issue for other projects 

[#560] Double 1px solid in dropdown separator

---

CHANGELOG.md
script/test
scss/bitstyles/base/font-face/_index.scss
scss/bitstyles/settings/_typography.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #559 
- Font-file location is now set by a variable
- Updates tests to use a different  webfont name instead of a standard `sans-serif`

[#559] Allow font base url to be configured

---

CHANGELOG.md
scss/bitstyles/base/typography/_index.scss
scss/bitstyles/generic/_normalize.scss
scss/bitstyles/settings/_typography.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #561 
- Default margins for heading elements and paragraphs can now be specified with the `$margin-heading` and `$margin-paragraph` variables respectively
- The default margin for paragraphs is now `0`

[#561] Add variable to handle margins in base/typography

---

CHANGELOG.md
scss/bitstyles.import.scss
scss/bitstyles.scss
scss/bitstyles/settings/_breakpoints.scss
scss/bitstyles/settings/_link.scss
scss/bitstyles/tools/_link.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #558 
- Renames the link variables so they make more sense within the Sass module system, and fit the naming scheme for other modules
- More properties are now set by variables
- Fixes the missing imports & forwards that was breaking some link overrides
- Corrected naming of breakpoints variables to match the scheme, and avoid duplication of the module name in the variable names

[#558] Rename link variables

---

CHANGELOG.md
scss/bitstyles/organisms/modal/_modal.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #574
- Modals now only show scrollbars (on OSes/configs where scrollbars are shown) when they’re needed
|before|after|
|--|--|
|<img width="961" alt="Screenshot 2022-01-03 at 17 01 00" src="https://user-images.githubusercontent.com/2479422/147952376-17049934-c9e3-42ca-bef6-bb97805e8b3e.png">|<img width="961" alt="Screenshot 2022-01-03 at 17 00 50" src="https://user-images.githubusercontent.com/2479422/147952398-6ceffa91-18c3-46fc-87ff-e6cc6b0910ab.png">|

[#574] modal scrollbars when external mouse is connected

---

CHANGELOG.md
scss/bitstyles/utilities/font/_font.scss
scss/bitstyles/utilities/font/_settings.scss
scss/bitstyles/utilities/font/font.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #583 
- Adds new `u-font` classes for spcifying font-family. Defaults to just header & body font-stacks

[#583] add utility font family

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/base/html/_html.scss
scss/bitstyles/base/html/_index.import.scss
scss/bitstyles/base/html/_index.scss
scss/bitstyles/base/html/_settings.scss
scss/bitstyles/base/html/html.stories.mdx
scss/bitstyles/base/typography/_index.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #586 
- `html` styles are now split out from the typography base styles
- color & background color on the `html` element can now be specified with sass variables

[#586] variables to set color background color of html

---

CHANGELOG.md
scss/bitstyles/settings/_color-palette.scss
scss/bitstyles/tools/_palette.scss

Fixes #587 
- Default key-name to return when asking for a color without specifying it (e.g. `palette.get('white')`) can now be set using `$bitstyles-color-palette-default-key`

[#587] variable to specify default value for palette get

---

CHANGELOG.md
scss/bitstyles/atoms/card/_card.scss
scss/bitstyles/tools/_properties.scss
scss/bitstyles/utilities/bg/_bg.scss
scss/bitstyles/utilities/border/_border.scss
scss/bitstyles/utilities/col-span/_col-span.scss
scss/bitstyles/utilities/col-start/_col-start.scss
scss/bitstyles/utilities/display/_display.scss
scss/bitstyles/utilities/fg/_fg.scss
scss/bitstyles/utilities/flex/_flex.scss
scss/bitstyles/utilities/font/_font.scss
scss/bitstyles/utilities/gap/_gap.scss
scss/bitstyles/utilities/grid-cols/_grid-cols.scss
scss/bitstyles/utilities/items/_items.scss
scss/bitstyles/utilities/justify/_justify.scss
scss/bitstyles/utilities/margin/_margin.scss
scss/bitstyles/utilities/overflow/_overflow.scss
scss/bitstyles/utilities/padding/_padding.scss
scss/bitstyles/utilities/row-start/_row-start.scss
scss/bitstyles/utilities/self/_self.scss
scss/bitstyles/utilities/text/_index.scss
scss/bitstyles/utilities/z-index/_z-index.scss

Fixes #597
The following changes are contained in this pull request
Renames:
- `tools/_directional-properties.scss` -> `tools/_properties.scss`
- `output-properties()` -> `output()`
- `output-directional-properties()` -> `output-directional()`
The result is that the three different generators are accessed as follows (examples show old -> new):
`directional-properties.output-directional-properties()` -> `properties.output-directional()`
`directional-properties.output-properties()` -> `properties.output()`
`directional-properties.output-block()` -> `properties.output-block()`

[#597] Renaming directional-properties

---

scss/bitstyles/atoms/avatar/avatar.stories.mdx
scss/bitstyles/atoms/badge/_badge.scss
scss/bitstyles/atoms/badge/badge.stories.mdx
scss/bitstyles/atoms/bordered-header/bordered-header.stories.mdx
scss/bitstyles/atoms/card/card.stories.mdx
scss/bitstyles/atoms/content/content.stories.mdx
scss/bitstyles/atoms/dl/dl.stories.mdx
scss/bitstyles/atoms/dropdown/dropdown.stories.mdx
scss/bitstyles/atoms/flash/flash.stories.mdx
scss/bitstyles/atoms/icon/icon.stories.mdx
scss/bitstyles/atoms/link/link.stories.mdx
scss/bitstyles/atoms/topbar/topbar.stories.mdx
scss/bitstyles/ui/icons.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #612 
- Updates the atoms’ docs in storybook to reflect the current available settings, and the defaults
- DRIVE-BY fixes an issue with buttons in badges

[#612] Update atoms/content documentation

---

CHANGELOG.md
scss/bitstyles/organisms/sidebar/_settings.scss
scss/bitstyles/organisms/sidebar/_sidebar.scss
scss/bitstyles/ui/sidebar.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #588
- Sidebar organism can be positioned on the left or right, specified using a variable

[#588] allow sidebar organism to change sides

---

CHANGELOG.md
package.json
scss/bitstyles/settings/typography.stories.mdx
scss/bitstyles/utilities/absolute-center/absolute-center.stories.mdx
scss/bitstyles/utilities/aspect-ratio/aspect-ratio.stories.mdx
scss/bitstyles/utilities/bg/bg.stories.mdx
scss/bitstyles/utilities/border/border.stories.mdx
scss/bitstyles/utilities/box-shadow/box-shadow.stories.mdx
scss/bitstyles/utilities/col-span/col-span.stories.mdx
scss/bitstyles/utilities/col-start/col-start.stories.mdx
scss/bitstyles/utilities/display/display.stories.mdx
scss/bitstyles/utilities/drop-shadow/drop-shadow.stories.mdx
scss/bitstyles/utilities/fg/fg.stories.mdx
scss/bitstyles/utilities/flex/flex.stories.mdx
scss/bitstyles/utilities/font/font.stories.mdx
scss/bitstyles/utilities/gap/gap.stories.mdx
scss/bitstyles/utilities/grid-cols/grid-cols.stories.mdx
scss/bitstyles/utilities/items/items.stories.mdx
scss/bitstyles/utilities/justify/justify.stories.mdx
scss/bitstyles/utilities/margin/margin.stories.mdx
scss/bitstyles/utilities/overflow/overflow.stories.mdx
scss/bitstyles/utilities/padding/_index.scss
scss/bitstyles/utilities/padding/_settings.scss
scss/bitstyles/utilities/padding/padding.stories.mdx
scss/bitstyles/utilities/row-start/row-start.stories.mdx
scss/bitstyles/utilities/self/self.stories.mdx
scss/bitstyles/utilities/sr-only/sr-only.stories.mdx
scss/bitstyles/utilities/text/text.stories.mdx
scss/bitstyles/utilities/z-index/z-index.stories.mdx
yarn.lock

Fixes #487 
Updates docs, and provides customisation guides for utility classes:
- aspect-ratios
- bg 
- border
- box-shadow
- col-span
- col-start
- display
- drop-shadow
- fg
- flex
- items
- font
- gap
- grid-cols
- items
- justify
- margin
- overflow
- items
- justify
- padding
- row-start
- self
- sr-only
- text
- z-index
Also drive-by:
- remove the `positive` key from padding class, it doesn’t make sense as `negative` can never be used
- Updates storybook, as the build was failing due to webpack & post-css versions not handling `:exports` directive. That added the eslint-storybook plugin, and updated to better handle webpack v5 (which we need for the colors exports to work)

[#487] Add customisation guides

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/utilities/min-height/_index.scss
scss/bitstyles/utilities/min-width/_index.import.scss
scss/bitstyles/utilities/min-width/_index.scss
scss/bitstyles/utilities/min-width/_settings.scss
scss/bitstyles/utilities/min-width/min-width.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #634 
- Adds a min-width utility class, with just `0` and no breakpoints as the default configuration

[#634] Add utility: min-width

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/utilities/max-width/_index.import.scss
scss/bitstyles/utilities/max-width/_index.scss
scss/bitstyles/utilities/max-width/_settings.scss
scss/bitstyles/utilities/max-width/max-width.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #646 
- Adds max-width utility class with `100vw` in the default configuration, at no breakpoints

[#646] Add utility: max-width

---

package.json
yarn.lock

- Ran `yarn upgrade`
- Forces resolution of trim to version 1.0.0
Still 5 vulnerabilities left in storybook dependencies, that according to https://github.com/storybookjs/storybook/issues/14603#issuecomment-1105006210 will be fixed when storybook 7.0 is released (goes alpha in “some weeks”)

Update dependencies 2022-04-28

---

CHANGELOG.md
script/test
scss/bitstyles/base/input-checkbox/_index.scss
scss/bitstyles/base/input-radio/_index.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #721 
When in a flex layout, if the sibling content’s min-content width (which is taken as the min-width of an element in a flex layout) is larger then the available space, the checkbox/radio would be crushed horizontally. That would happen when e.g. the text label next to the input has a long word, or if the available space is very narrow.
- Checkboxes and radios now have `flex-shrink: 0` to avoid distortion when placed in a flex layout
|Before|After|
|--|--|
|<img width="98" alt="Screenshot 2022-12-12 at 15 09 06" src="https://user-images.githubusercontent.com/2479422/207069534-91cf98ce-387f-4af9-91cc-7a4806ed3023.png">|<img width="98" alt="Screenshot 2022-12-12 at 15 23 30" src="https://user-images.githubusercontent.com/2479422/207069578-4220a516-ae0c-4ce6-ae30-11b354260220.png">| …

[#721] No flex-shrink for radios & checkboxes

---

scss/bitstyles/atoms/card/card.stories.mdx
scss/bitstyles/atoms/dl/dl.stories.mdx
scss/bitstyles/organisms/modal/modal.stories.mdx
scss/bitstyles/settings/breakpoints.stories.mdx
scss/bitstyles/ui/dl.stories.mdx
scss/bitstyles/ui/forms.stories.mdx
scss/bitstyles/ui/stats.stories.mdx
scss/bitstyles/ui/ui-components.mdx
scss/bitstyles/utilities/col-span/col-span.stories.mdx
scss/bitstyles/utilities/col-start/col-start.stories.mdx
scss/bitstyles/utilities/display/display.stories.mdx
scss/bitstyles/utilities/gap/gap.stories.mdx
scss/bitstyles/utilities/grid-cols/grid-cols.stories.mdx
scss/bitstyles/utilities/row-start/row-start.stories.mdx

Fixes #691
Cleanup after #674 — renames all the uses of `u-gap-m` in our documentation to `u-gap-l`, to match the renamed classname

[#691] Rename u-gap-m to u-gap-l

---

CHANGELOG.md
scss/bitstyles/base/forms/_index.scss
scss/bitstyles/base/html/_index.scss
scss/bitstyles/settings/_typography-responsive.scss
scss/bitstyles/settings/_typography.scss
test/scss/fixtures/bitstyles.css

Fixes #677
- `settings/typography/$line-heights` is now ordered by magnitude
- adjusted `settings/typography-responsive.$typographic-scale` to output the same styles as before
- removes `settings/typography.$line-height-base`

[#677] Line-height cleanup

---

CHANGELOG.md
scss/bitstyles/generic/_box-sizing.scss
scss/bitstyles/settings/_layout.scss
scss/bitstyles/settings/layout.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #686 
- Updates the height of body to `stretch`, to ensure it respects the variable height of mobile browser viewports
- The list of elements that style is applied to is now configurable
- Adds docs with an example of the layout

[#686] Html & body stretch

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/utilities/width/_index.import.scss
scss/bitstyles/utilities/width/_index.scss
scss/bitstyles/utilities/width/_settings.scss
scss/bitstyles/utilities/width/width.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #697 
Adds a width utility class, with basic defaults and stories

[#697] Add utility: width

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/utilities/white-space/_index.import.scss
scss/bitstyles/utilities/white-space/_index.scss
scss/bitstyles/utilities/white-space/_settings.scss
scss/bitstyles/utilities/white-space/white-space.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #699 
- Adds a white-space utility class with minimal defaults

[#699] Add utility: white-space

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/utilities/text-decoration/_index.import.scss
scss/bitstyles/utilities/text-decoration/_index.scss
scss/bitstyles/utilities/text-decoration/_settings.scss
scss/bitstyles/utilities/text-decoration/text-decoration.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #719 
- Adds a text-decoration-line utility class

[#719] Add utility: text-decoration

---

scss/bitstyles.scss
scss/bitstyles/utilities/grid-rows/_index.import.scss
scss/bitstyles/utilities/grid-rows/_index.scss
scss/bitstyles/utilities/grid-rows/_settings.scss
scss/bitstyles/utilities/grid-rows/grid-rows.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #716 
- Adds grid-rows utility class, with example
|Small viewport| Large viewport|
|--|--|
|![utilities grid rows u grid rows max content](https://user-images.githubusercontent.com/2479422/209147076-bd302dcf-4e4c-48e4-8cb2-dd112c23bc9e.png)|![utilities grid rows u grid rows max content(1)](https://user-images.githubusercontent.com/2479422/209147120-7f858190-1a9d-4706-9a3f-44f2e88f2dab.png)|

[#716] Add utility: grid-row

---

CHANGELOG.md
scss/bitstyles/exports/_animation.scss
scss/bitstyles/exports/_breakpoints.scss
scss/bitstyles/exports/_color-palette.scss
scss/bitstyles/exports/_layout.scss
scss/bitstyles/exports/_shadows.scss
scss/bitstyles/exports/_typography.scss
scss/bitstyles/settings/animation.stories.mdx
scss/bitstyles/settings/breakpoints.stories.mdx
scss/bitstyles/settings/color-palette.stories.mdx
scss/bitstyles/settings/shadows.stories.mdx
scss/bitstyles/settings/sizes.stories.mdx
scss/bitstyles/settings/typography.stories.mdx

Fixes #693 
- Adds export files for all the design tokens
- Adds documentation for using the design tokens in JS
```js
import breakpoints from '../exports/_breakpoints.scss';
console.log(breakpoints['s']); // 'screen and (max-width:29.9375em)'
console.log(breakpoints['m']); // 'screen and (min-width:30em)'
console.log(breakpoints['l']); // 'screen and (min-width:55em)'
// …
```
```js
import colorPalette from '../exports/_color-palette.scss';
console.log(colorPalette['brand-1.lighter']); // '#f4f2ff'
console.log(colorPalette['brand-1.light']); // '#c8bfff'
console.log(colorPalette['brand-1.base']); // '#644dff'
// …
```

[#693] Export design tokens to JS

---

scss/bitstyles/atoms/button-colors/button-colors.stories.mdx

Updates storybook documentation for button colors

[#730] update docs for button colors

---

scss/bitstyles/utilities/justify/_settings.scss
scss/bitstyles/utilities/justify/justify.stories.mdx
test/scss/fixtures/bitstyles.css

This PR updates the default configuration for the `u-justify` utility class to include `justify-content: center`
#733 

Add justify-content: center to the default configuration for the justify utility class

---

.storybook/helpers.js
CHANGELOG.md
scss/bitstyles/atoms/skip-link/_index.scss
scss/bitstyles/atoms/skip-link/_settings.scss
scss/bitstyles/atoms/skip-link/skip-link.stories.js
scss/bitstyles/atoms/skip-link/skip-link.stories.mdx
scss/bitstyles/base/anchor/Link.js
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-use-all.scss
test/scss/test-use-each.scss
test/scss/test-use-layers.scss

Fixes #764 
- New styles for the skip link
- Component now has a hover states, so that the component still indicates their affordance to those who mix use of keyboard and pointer
- `git fetch`
- `git checkout feature/764-update-skip-link`
- `yarn`
- `yarn storybook`
- navigate to atoms/skip-link component
Check:
Check:

[#764] Update skip-link

---

.storybook/helpers.js
CHANGELOG.md
scss/bitstyles/atoms/_index.scss
scss/bitstyles/atoms/content/_settings.scss
scss/bitstyles/atoms/switcher/Switcher.js
scss/bitstyles/atoms/switcher/_index.scss
scss/bitstyles/atoms/switcher/_settings.scss
scss/bitstyles/atoms/switcher/switcher.stories.js
scss/bitstyles/atoms/switcher/switcher.stories.mdx
scss/bitstyles/design-tokens/_content.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-use-all.scss
test/scss/test-use-each.scss
test/scss/test-use-layers.scss

Part of #779 
New css layout component that switches from a horizontal row to vertical stack when the width is below a certain threshold, or the number of children is over a certain limit.
| Larger viewport | Smaller viewport |
|--|--|
|<img width="601" alt="Screenshot 2023-05-23 at 17 11 47" src="https://github.com/bitcrowd/bitstyles/assets/2479422/9261a61d-871f-4069-b216-868da1c01eee">|<img width="421" alt="Screenshot 2023-05-23 at 17 12 10" src="https://github.com/bitcrowd/bitstyles/assets/2479422/57470ab5-a714-4051-b028-22ce490d0bca">|
- `git fetch`
- `git checkout feature/779-add-some-layout-primitives-2`
- `yarn`
- `yarn storybook`
- navigate to atom/switcher component
Check:
Check:

[#779] Add some layout primitives (switcher)

---

.github/workflows/run-checks.yml

New changes on the github actions workflow. We now need to specify the node version. [See](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow)

Driveby - Fix CI node version.

---

CHANGELOG.md
scss/bitstyles/atoms/_index.scss
scss/bitstyles/atoms/button/Button.js
scss/bitstyles/atoms/stack/Stack.js
scss/bitstyles/atoms/stack/_index.scss
scss/bitstyles/atoms/stack/_settings.scss
scss/bitstyles/atoms/stack/stack.stories.js
scss/bitstyles/atoms/stack/stack.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-use-all.scss
test/scss/test-use-each.scss
test/scss/test-use-layers.scss

Part of #779 
- Stack component CSS
- Adds a Stack JS component, stories, and docs to go with it
- `git fetch`
- `git checkout feature/779-add-some-layout-primitives`
- `yarn`
- `yarn storybook`
- navigate to atoms/ component
Check:
Check:

[#779] Add some layout primitives (stack)

---

CHANGELOG.md
package.json

- Bumps version number to 6.1.0
- Updates changelog

Bump version number
