README.md

Fixes #192.
- Updates the README sections detailing adding bitstyles to your Rails asset pipeline with more correct info regarding Rails 4

Update rails readme info

---

README.md
package.json

Fixes #213 .
- Corrects the version number stated in the installation instructions

Corrects the tag named in the installation instructions

---

.travis.yml

Partial fix for #164.
- Initial `.travis.yml`, currently just running `npm run lint` and `npm run build`.

[#164] add ci tests

---

README.md

Fixes #235
-  New intro for the README:
- States the complexity level & compares to bootstrap/foundation
- Short description of the two main ways its object classes are intended to be used.

[#235] readme intro

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #267 
- Removed unnecessary checklist items
- Removed unnecessary title & punctuation
- Corrected spelling
- Updated language to be clearer what’s the expected usage of the checklists.

[#267] update github pr template

---

scripts/styleguide.sh
styleguide/assets/stylesheets/styleguide-colors.css
styleguide/assets/stylesheets/styleguide-theme.css

Fixes #247 
- Uses bitcrowd’s new brand colours
- Updated typography

[#247] styleguide design

---

lib/bitstyles/version.rb
package.json

Bump version

---

scss/bitstyles/layout/content/_.scss
scss/bitstyles/layout/grid/_.scss
scss/bitstyles/layout/grid/grid.stories.js
scss/bitstyles/layout/list-inline/_.scss
scss/bitstyles/layout/object-cover/_.scss
scss/bitstyles/layout/topbar/_.scss
scss/bitstyles/objects/bordered-header/_.scss
scss/bitstyles/objects/button--icon/_.scss
scss/bitstyles/objects/button/_.scss
scss/bitstyles/objects/icon/_.scss
scss/bitstyles/objects/input/_.scss
scss/bitstyles/objects/label/_.scss
scss/bitstyles/objects/link/_.scss
scss/bitstyles/objects/overflow/_.scss
scss/bitstyles/tools/_all.scss
scss/bitstyles/tools/_bordered-header.scss
scss/bitstyles/tools/_button--icon.scss
scss/bitstyles/tools/_button.scss
scss/bitstyles/tools/_grid.scss
scss/bitstyles/tools/_icon.scss
scss/bitstyles/tools/_input.scss
scss/bitstyles/tools/_label.scss
scss/bitstyles/tools/_link.scss
scss/bitstyles/tools/_list-inline.scss
scss/bitstyles/tools/_object-cover.scss
scss/bitstyles/tools/_topbar.scss
scss/bitstyles/tools/content.scss
scss/bitstyles/utilities/background-color/_.scss
scss/bitstyles/utilities/color/_.scss
test/css-stats.json

Fixes #304 
- Adds mixins for all the classes previously missing them
- Fixes grid stories (whitespace)
- Adds a few missing `#{$bitstyles-namespace}`s

304 missing tools

---

package.json

bump version 0.10.1

---

package.json

once #332 is merged, bump version number

bump version number to 0.10.2

---

package.json
yarn.lock

Updates storybook/html & storybook/addons. This fixes reported security vulnerabilities in sub-dependencies

Update dependencies 2020-08-26

---

yarn.lock

Bumps prismjs version to avoid a vulnerability

Upgrade prismjs

---

yarn.lock

Updates prismjs due to vulnerability

2020-11-02-update-dependencies

---

scss/bitstyles.scss
scss/bitstyles/objects/button--danger/_.scss
scss/bitstyles/objects/button--danger/button--danger.stories.mdx
scss/bitstyles/objects/button--danger/settings.scss
scss/bitstyles/settings/_global.color-palette.scss

Adds a 'danger' button type
Looks like (only red on hover):

add button danger

---

scss/bitstyles.scss
scss/bitstyles/objects/button--nav/_.scss
scss/bitstyles/objects/button--nav/button--nav.stories.mdx
scss/bitstyles/objects/button--nav/settings.scss

Add a button--nav component.
Looks like:

Add button--nav

---

scss/bitstyles.scss
scss/bitstyles/objects/avatar/_.scss
scss/bitstyles/objects/avatar/avatar.stories.mdx
scss/bitstyles/objects/avatar/settings.scss

Adds an avatar object, round-clipped image.
Looks like:

add avatar object

---

.github/workflows/deploy-docs.yml
package.json
yarn.lock

The deploy-to-github-pages action that happens on merging to `main` fails when building storybook. Debugging here

Hot fix/fix deploy

---

scss/bitstyles.scss
scss/bitstyles/atoms/button--ui/_.scss
scss/bitstyles/atoms/card/settings.scss
scss/bitstyles/atoms/content/_.scss
scss/bitstyles/atoms/content/settings.scss
scss/bitstyles/atoms/flash/_.scss
scss/bitstyles/atoms/flash/flash.stories.mdx
scss/bitstyles/atoms/flash/settings.scss
scss/bitstyles/organisms/modal/modal.stories.mdx
scss/bitstyles/organisms/notification-center/_.scss
scss/bitstyles/organisms/notification-center/notification-center.stories.mdx
scss/bitstyles/ui/flashes.stories.mdx
scss/bitstyles/ui/forms.stories.mdx
scss/bitstyles/ui/notifications.stories.mdx
scss/bitstyles/utilities/margin/_.scss
scss/bitstyles/utilities/margin/settings.scss

Fixes #406 
Adds a simple notification component, and a notification with buttons.
Looks like:

[#406] Add component: notifications

---

CHANGELOG.md

Fixes #449 
Adds an initial CHANGELOG.md, detailing the changes of v1.0.0 onwards

[#449] Add a changelog.md

---

CHANGELOG.md

Fixes #463 
All the titles of each release in the changelog now link to that release on github

[#463] Add links to changelog

---

CHANGELOG.md
package.json

Bump version 1.3.0

---

README.md

Fixes #523
- Adds link to BitstylesPhoenix in the README

[#523] Link to bitstyles_phoenix

---

.github/workflows/run-checks.yml
scss/bitstyles/generic/_reset.scss
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css

Fixes #547
- Adds basic github action for linting & testing

[#547] Testing on CI

---

CHANGELOG.md
scss/bitstyles/utilities/gap/_settings.scss
test/scss/fixtures/bitstyles.css

add u-gap-xs

---

CHANGELOG.md
package.json

Bump version 3.1.0

---

CHANGELOG.md
package.json

Bump version 4.0.0

---

.github/workflows/run-checks.yml
README.md

- update workflow name
- add badge for CI to README
- update npm badge to a fancier one
Note: we may need to update which workflow is required for PRs as the name changed...

Update workflow name and badges

---

README.md

Fixes the rendering of the font license link in the README.

Fix broken font-license link

---

CHANGELOG.md

Fixes #622
- Explicit list of changed classes

[#622] List changed utility class in changelog

---

CHANGELOG.md
package.json

- Bumps version
- updates changelog

Bump version 4.1.0

---

CHANGELOG.md
package.json

- Updates version number & changelog

Bump version 4.2.0

---

CHANGELOG.md
package.json

- update changelog
- update version number

Bump version 4.3.0

---

CHANGELOG.md
package.json

Bump version 5.0.0-alpha

---

.github/workflows/run-checks.yml
scss/bitstyles/atoms/avatar/avatar.stories.mdx

Fixes #680 
- Adds build-storybook to CI

[#680] Check storybook builds on CI

---

test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
yarn.lock

Update Dependencies 2022-10-19

---

CHANGELOG.md

Missed a commit on the last PR

Changelog tweaks

---

CHANGELOG.md
scss/bitstyles.scss
scss/bitstyles/atoms/button-colors/_index.scss
scss/bitstyles/atoms/button-colors/_settings.scss
scss/bitstyles/atoms/button-colors/button-colors.stories.mdx
scss/bitstyles/atoms/button/_index.scss
scss/bitstyles/atoms/button/_settings.scss
scss/bitstyles/atoms/button/button.stories.mdx
scss/bitstyles/base/html/_index.import.scss
scss/bitstyles/base/html/_index.scss
scss/bitstyles/base/html/_settings.scss
scss/bitstyles/base/html/html.stories.mdx
scss/bitstyles/base/themes/_index.scss
scss/bitstyles/base/themes/themes.stories.mdx
scss/bitstyles/settings/_color-palette.scss
scss/bitstyles/settings/_themes.import.scss
scss/bitstyles/settings/_themes.scss
scss/bitstyles/settings/themes.stories.mdx
scss/bitstyles/tools/_button.scss
scss/bitstyles/tools/_custom-properties.scss
scss/bitstyles/tools/_themes.scss
scss/bitstyles/ui/buttons.stories.mdx
test/scss/fixtures/bitstyles-overrides.css
test/scss/fixtures/bitstyles.css
test/scss/test-import-all.scss
test/scss/test-import-each.scss
test/scss/test-use-all.scss
test/scss/test-use-each.scss

Fixes #683
- Adds text/background-color theming
- Adds Button-colors theming

[#683] Add theming

---

CHANGELOG.md
package.json

Bump version 5.0.0

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #755 
- Updates the PR template. Adds more detailed instructions for how to QA the changes for designers, and for developers with less context on the project.

[#755] Update PR template

---

CHANGELOG.md
package.json

- Updates version number
- Updates changelog
None.

Bump version 6.0.0

---

CHANGELOG.md
package.json

- Updates version numbers in package.json & CHANGELOG
- Updates CHANGELOG

Bump version 6.2.0
